pihole:
   container_name: pihole
   hostname: pihole
   image: pihole/pihole:latest
   restart: unless-stopped
   environment:
      - ServerIP=172.17.0.3
      - PROXY_LOCATION=pihole
   ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8182:80'
      - '8183:443'
